### PR TITLE
[DPE-3040] Update snap

### PR DESCRIPTION
**Pull request by dragomirp**
Update to pgbouncer 1.21

### CODE REVIEW

**Comment by dragomirp** [comment]
The `--reboot`, the [docs](https://www.pgbouncer.org/usage.html#command-line-switches) recommend using rolling restart on the same socket. Should I try to get rid of it in this PR?

**Comment by marceloneppel** [comment]
> The `--reboot`, the [docs](https://www.pgbouncer.org/usage.html#command-line-switches) recommend using rolling restart on the same socket. Should I try to get rid of it in this PR?

IMO, we can schedule it for the next pulse (with a new ticket) to avoid that it impacts the remaining tasks from this pulse (or just work on it after them if they are finished earlier).

**Review by marceloneppel — APPROVED** [review]

**Review by taurus-forever — APPROVED** [review]
Tnx!

**Comment by taurus-forever** [comment]
> The `--reboot`, the [docs](https://www.pgbouncer.org/usage.html#command-line-switches) recommend using rolling restart on the same socket. Should I try to get rid of it in this PR?

IMHO, new ticket as it is a deprecation notification only. The `--reboot` should still do the job.
Sure we need to plane migration to the socket the next pulse.

**Comment by dragomirp** [comment]
> > The `--reboot`, the [docs](https://www.pgbouncer.org/usage.html#command-line-switches) recommend using rolling restart on the same socket. Should I try to get rid of it in this PR?
> 
> IMHO, new ticket as it is a deprecation notification only. The `--reboot` should still do the job. Sure we need to plane migration to the socket the next pulse.

Created [DPE-3058](https://warthogs.atlassian.net/browse/DPE-3058) and [DPE-3059](https://warthogs.atlassian.net/browse/DPE-3059) to track this.

**Pull request merged**
